### ISSUE TITLE
Test failing with Python 3.10

### ISSUE THREAD

**Issue by cverna** [containerbuildsystem/osbs-client#1028]
Got the following report while trying to rebuild osbs-client in Fedora 35 --> https://bugzilla.redhat.com/show_bug.cgi?id=1936939

**Comment by MartinBasti** [comment]
For me it looks more related to a newer git than py3.10

**Comment by rcerven** [comment]
yeah new git feature seems like

Initialized empty Git repository in /tmp/pytest-of-mockbuild/pytest-0/test_get_repo_info0/repo/.git/
----------------------------- Captured stderr call -----------------------------
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
fatal: not in a git directory

**Comment by MartinBasti** [comment]
This is the fix, can somebody explain me, why git commands are randomly failing when they are executed too fast? Some file write issues?

```diff

diff --git a/tests/utils/test_utils.py b/tests/utils/test_utils.py
index 3f4aea1..b435949 100644
--- a/tests/utils/test_utils.py
+++ b/tests/utils/test_utils.py
@@ -7,6 +7,8 @@ of the BSD license. See the LICENSE file for details.
 """
 from __future__ import absolute_import
 
+import time
+
 from flexmock import flexmock
 import os
 import os.path
@@ -538,13 +540,19 @@ def test_get_repo_info(tmpdir):
 
 def initialize_git_repo(rpath, files=None):
     subprocess.Popen(['git', 'init', rpath])
+    time.sleep(2)
     subprocess.Popen(['git', 'config', 'user.name', '"Gerald Host"'], cwd=rpath)
+    time.sleep(2)
     subprocess.Popen(['git', 'config', 'user.email', '"ghost@example.com"'], cwd=rpath)
+    time.sleep(2)
     first_commit_ref = None
     for f in files or []:
         subprocess.Popen(['touch', f], cwd=rpath)
+        time.sleep(2)
         subprocess.Popen(['git', 'add', f], cwd=rpath)
+        time.sleep(2)
         subprocess.Popen(['git', 'commit', '-m', 'new file {0}'.format(f)], cwd=rpath)
+        time.sleep(2)
         if not first_commit_ref:
             sleep(2)  # when rev-parse is called too early after first commit, it fails
             first_commit_ref = subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=rpath)

```

**Comment by MartinBasti** [comment]
Lol, popen() is not waiting, this worked by accident whole time

**Comment by cverna** [comment]
Thanks for looking at it :+1:
